src/main/java/br/com/cge/repositoryFiles/managedBeans/OrgaoMBean.java
package br.com.cge.repositoryFiles.managedBeans;


import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import br.com.cge.repositoryFiles.dao.OrgaoDAO;
import br.com.cge.repositoryFiles.model.Orgao;


@ManagedBean
@RequestScoped
public class OrgaoMBean {
	private Orgao orgao = new Orgao();
	
	
    public String cadastraOrgao() throws SQLException {

               OrgaoDAO orgaoDao = new OrgaoDAO();

               if (orgaoDao.insertOrgao(orgao)) {
            	   orgao = new Orgao();
                    FacesContext.getCurrentInstance().addMessage(
                     null, new FacesMessage(FacesMessage.SEVERITY_INFO,
                     "Orgão cadastrado com sucesso!", "Sucesso!"));
               } else {
                    FacesContext.getCurrentInstance().addMessage(
                       null, new FacesMessage(FacesMessage.SEVERITY_ERROR,"Erro no cadastro do Orgão!",
                       "Erro!"));
               }
             
         return "";
    }
    
    public Orgao getOrgao() {
        return orgao;
    }

    public void setOrgao(Orgao orgao) {
        this.orgao = orgao;
    }
   
    private List<Orgao> siglas = new ArrayList<Orgao>();

	public List<Orgao> getLista() throws Exception {
		OrgaoDAO orgaodao = new OrgaoDAO();
	    this.siglas = orgaodao.listarOrgaos();

	    return siglas;
	}

	public void setLista(ArrayList<Orgao> siglas) {
	    this.siglas= siglas;
	}
   
   
}

src/main/webapp/app/cadFileUpload.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	
	xmlns:util="http://java.sun.com/jsf/composite/components"
	
	xmlns:p="http://primefaces.org/ui">
	<h:head>
		<title>Upload</title>
		
		
	</h:head>
	<h:body>
	
	
	
		<util:menuLayout managedBeanMenu="#{UploadMB}">
			
		</util:menuLayout>
	
		 <p:messages escape="false" showDetail="true" autoUpdate="true" closable="true" style="width:80%; height:8%; margin-left: auto; margin-right: auto; margin-top:2%;"/> <!-- severity="info" -->
	
     	<h:form prependid="false" enctype="multipart/form-data" autoUpdate="true" style="margin-top:5%;"> <!--  -->
	       	<div align="center">
	            <p:outputLabel value="Primeiro selecione o arquivo desejado e submeta ao Upload."/>
			    <br/>
			    <p:fileUpload mode="simple" value="#{UploadMB.uploadedFile}" style="margin-right:8%; margin-top:1%;" />
			    
			    <p:commandButton value="Upload" action="#{UploadMB.upload()}" ajax="false"  styleClass="ui-button-success"/>
			    <br/>
			</div>
		
	       	<p:panelGrid columns="2" class="table table-hover table-striped table-bordered" style="width:45%; height: 8%; margin-left: auto; margin-right: auto; margin-top:3%; margin-bottom:5%;">
	             <p:outputLabel for="descricao" value="Descrição:" />
	             <p:inputTextarea id="descricao" value="#{UploadMB.fileupload.descricao}" />
	             
	             <p:outputLabel id="tipoDoc" for="tipoDoc" value="Tipo do Documento:" />
	             <p:outputLabel id="tipoDocValue" for="tipoDocValue" value="#{UploadMB.fileupload.tipoDoc}" />      
	         </p:panelGrid>
          
          <p:inputText type="hidden" id="path" value="#{UploadMB.fileupload.path}"> </p:inputText>     
          <p:inputText type="hidden" id="tipoDocHidden" value="#{UploadMB.fileupload.tipoDoc}"> </p:inputText>  
          <center> <p:commandButton  value="Cadastrar" icon="ui-icon-star"
                 action="#{UploadMB.cadastraFile()}" autoUpdate="true">
                </p:commandButton>
               &nbsp;&nbsp;&nbsp;&nbsp;
                <p:commandButton value="Gerar PDF" ajax="false" actionListener="#{UploadMB.descarregar}">
					  <p:fileDownload value="#{UploadMB.file}" />					  
				</p:commandButton>	
		  </center>
          <br></br>
     </h:form>
     
     <util:footerLayout managedBeanFooter="#{UploadMB}">
			
	</util:footerLayout>
     
	</h:body>
</html>

src/main/webapp/app/cadOrgao.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:util="http://java.sun.com/jsf/composite/components"
	xmlns:p="http://primefaces.org/ui">
	<h:head>
		<title>Cadastro de Órgão</title>
		<h:outputStylesheet name="css/style.css"/>	
	</h:head>
	<h:body >
	
		<util:menuLayout managedBeanMenu="#{orgaoMBean}">
		</util:menuLayout>
	     <h:form>
	     	<h2 style="width:50%; margin-left: auto; margin-right: auto">Faça seu Cadastro de Órgão aqui</h2>
	          <p:messages id="messages" >
	          		<p:effect type="fade" event="load" delay="2000" />
	          </p:messages>
	          
	          		 <p:panelGrid id="panelOrgao" class="table table-hover table-striped table-bordered" style="width:50%; margin-left: auto; margin-right: auto;" columns="2">
		                 <p:outputLabel for="sigla" value="Sigla do Órgão:" />
		                 <p:inputText id="sigla" value="#{orgaoMBean.orgao.sigla}" />
		                 <p:outputLabel for="descricaoOrgao" value="Nome Completo do Órgão:" />
		                 <p:inputText id="descricaoOrgao" value="#{orgaoMBean.orgao.descricaoOrgao}" />
	              	 </p:panelGrid>
		             <center><p:commandButton value="Cadastrar" icon="ui-icon-star"   action="#{orgaoMBean.cadastraOrgao}" update="messages,panelOrgao" /></center>
	          
	     </h:form>
	</h:body>
</html>

src/main/webapp/app/cadUsuario.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	
	xmlns:util="http://java.sun.com/jsf/composite/components"
	
	xmlns:p="http://primefaces.org/ui">
	<h:head>
		<title>Cadastro de Usuário</title>
	</h:head>
	<h:body>
		<util:menuLayout managedBeanMenu="#{usuarioMBean}">
			
		</util:menuLayout>
	     <h:form>
	     	<h2 style="width:50%; margin-left: auto; margin-right: auto">Cadastro de Usuário</h2>
	          <p:messages id="messages" />
	          <div class="ui-g-12" style="margin-top: 10px; margin-bottom: 10px; text-align: center;">
	           <p:outputLabel for="cpf" value="Informe o CPF do novo usuário: " />
	                <p:inputText style="margin:10px" id="cpf" value="#{usuarioMBean.usuario.cpf}" />  
	                
	          	  <p:commandButton  id="idButtonpesquisarUsuario" value="pesquisar" style="width: 180px; margin: 10px"   action="#{usuarioMBean.pesquisarUsuarioSEAP()}"  update="@all">
                        <p:tooltip value="pesquisar usuário no SEAP" for="idButtonpesquisarUsuario"/>
                    </p:commandButton>
	          </div>
	          <p:panelGrid  class="table table-hover table-striped table-bordered" style="width:50%; margin-left: auto; margin-right: auto;" columns="2">
	                
	                <p:outputLabel id="matricula" for="matricula" value="Matrícula:" />
	                <p:outputLabel id="matriculaValue" for="matriculaValue" value="#{usuarioMBean.usuario.matricula}" />
	                
	                <p:outputLabel id="nome" for="nome" value="Nome:" />
	                <p:outputLabel id="nomeValue" for="nomeValue" value="#{usuarioMBean.usuario.nome}" />
					
					
					<p:outputLabel id="emailInstitucional" for="emailInstitucional" value="Email Institucional:" />
					<p:outputLabel id="emailInstitucionalValue" for="emailInstitucionalValue" value="#{usuarioMBean.usuario.emailInstitucional}" />
					
			        <p:outputLabel id="orgao" for="orgao" value="orgao:" />
			        <p:outputLabel id="orgaovalue" for="orgaovalue" value="#{usuarioMBean.usuario.orgao}" />
			          
	          </p:panelGrid>
	          <center> <p:commandButton  value="Cadastrar" icon="ui-icon-star" action="#{usuarioMBean.cadastraUsuario}" update="messages"></p:commandButton></center>
	     </h:form>
	     
	     <util:footerLayout managedBeanFooter="#{DownloadMB}">
			
		</util:footerLayout>
	     
	</h:body>
</html>

src/main/webapp/app/download.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	
	xmlns:util="http://java.sun.com/jsf/composite/components"
	
	xmlns:p="http://primefaces.org/ui">
	<h:head>
		<title>Download</title>
	</h:head>
	<h:body>
	     
	     <util:menuLayout managedBeanMenu="#{DownloadMB}">
			
		</util:menuLayout>
	     
	     
     
	    
	     
	      <h:form> 
           <h2 style="width:70%; margin-left: auto; margin-right: auto">Meus arquivos carregados:</h2>
           <br/>
            <h:dataTable class="table table-hover table-striped table-bordered " value="#{DownloadMB.lista}" var="l" style="width:70%; margin-left: auto; margin-right: auto; .table-hover: b"> 
                <h:column> 
                    <f:facet name="header"><h:outputText value="Paths Files" /></f:facet>
                    <p:outputLabel value="#{l.path}" /> 
                </h:column> 
                <h:column> 
                    <f:facet name="header"><h:outputText value="Descrição" /></f:facet>
                    <p:outputLabel value="#{l.descricao}" /> 
                </h:column> 
                 <h:column> 
                    <f:facet name="header"><h:outputText value="Tipo" /></f:facet>
                    <p:outputLabel value="#{l.tipoDoc}" /> 
                </h:column> 
                
                
                <p:column headerText="Download">
		            <p:column headerText="Download">
		                <p:commandButton value="Download" ajax="false" actionListener="#{DownloadMB.descarregar(l.path)}" >
						  	<p:fileDownload value="#{DownloadMB.file}" />
						</p:commandButton>			
	                </p:column>
	                <br/>
	                <p:column headerText="Download">
	                	<f:facet name="header"><h:outputText value="Baixar/Ver" /></f:facet>
	               	 	<p:link href="#{l.path}">Ver no Navegador</p:link>
		               <!--  <p:commandButton immediate="true" value="Download" ajax="false" onclick="PrimeFaces.monitorDownload(start, stop);" icon="ui-icon-arrowthick-1-s">
		                    <p:fileDownload value="#{DownloadMB.file}" />
		                </p:commandButton> -->
		            </p:column>
	            </p:column>
            </h:dataTable> 
        </h:form>
	    <br/><br/><br/><br/>
	     	
	     
	     
	    <util:footerLayout managedBeanFooter="#{DownloadMB}">
			
		</util:footerLayout>
	     
	     
	     
	</h:body>
</html>

src/main/webapp/app/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	
	xmlns:util="http://java.sun.com/jsf/composite/components"
	
	xmlns:p="http://primefaces.org/ui">
	
	<h:body>
		<util:menuLayout managedBeanMenu="#{DownloadMB}">
			
		</util:menuLayout>
	
		
		<br/><br/><h3 style="width:75%; margin-left: auto; margin-right: auto">Tela Inicial</h3><br/><br/>
		
		<h:form> 
           <h2 style="width:60%; margin-left: auto; margin-right: auto">Meus arquivos carregados:</h2>
           <br/>
            <h:dataTable class="table table-hover table-striped table-bordered " value="#{DownloadMB.lista}" var="l" style="width:60%; margin-left: auto; margin-right: auto; .table-hover: b"> 
                <h:column> 
                    <f:facet name="header"><h:outputText value="Paths Files" /></f:facet>
                    <p:outputLabel value="#{l.path}" /> 
                </h:column> 
                <h:column> 
                    <f:facet name="header"><h:outputText value="Descrição" /></f:facet>
                    <p:outputLabel value="#{l.descricao}" /> 
                </h:column> 
                 <h:column> 
                    <f:facet name="header"><h:outputText value="Tipo" /></f:facet>
                    <p:outputLabel value="#{l.tipoDoc}" /> 
                </h:column> 
                
                <p:column headerText="Download">
		            <p:column headerText="Download">
	                <p:commandButton value="Download" ajax="false" actionListener="#{DownloadMB.descarregar(l.path)}" icon="ui-icon-arrowthick-1-s">
					  	<p:fileDownload value="#{DownloadMB.file}" />
					</p:commandButton>			
	                </p:column>
	                <br/>
	                <p:column headerText="Download">
	                	<f:facet name="header"><h:outputText value="Baixar/Ver" /></f:facet>
	               	 	<p:link href="#{l.path}">Ver no Navegador</p:link>
		            </p:column>
	            </p:column>
            </h:dataTable> 
        </h:form>
		<util:footerLayout managedBeanFooter="#{DownloadMB}">
		</util:footerLayout>
	</h:body>
</html>